# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(blank=True, max_length=15, null=True)),
                ('how_time', models.CharField(blank=True, max_length=15, null=True)),
                ('abilities_needed', django_mysql.models.ListTextField(models.CharField(max_length=20), size=6)),
            ],
        ),
    ]
