# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-11 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='carrier',
            new_name='field_of_work',
        ),
    ]
