# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20180212_1105'),
        ('job', '0003_job_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.EmployeeProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='user.EmployerProfile'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='job',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='JobOpportunity', to='job.Job'),
        ),
    ]
