# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180207_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='abilities_have',
        ),
    ]
