# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180208_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='123456a', max_length=16, verbose_name='password'),
        ),
    ]
