# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-10 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20180208_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='how_time',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
