# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-10 05:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_employeeprofile_how_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_time', models.CharField(blank=True, max_length=15, null=True)),
                ('field_of_work', models.CharField(blank=True, max_length=15, null=True)),
                ('abilities_have', django_mysql.models.ListTextField(models.CharField(max_length=20), size=6)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='abilities_have',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='field_of_work',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='how_time',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='work_schedule',
            field=models.ManyToManyField(blank=True, to='user.WorkSchedule'),
        ),
    ]
