# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-10 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20180210_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
