# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20180212_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.EmployeeProfile'),
        ),
    ]
